Areas/Admin/Controllers/AdminsController.cs
using MVC_BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_BookStore.Areas.Admin.Controllers
{
    public class AdminsController : Controller
    {
        DBBookStore db= new DBBookStore();
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult ProcessRegister(RegisterUser u)
        {
            var qtv = new QTV
            {
                HoTen = u.Name,
                TenDN = u.User,
                MK = u.Pass,
                NgaySinh = u.Born,
                
                SDT = u.Phone,
                Email = u.Email,
            };
            db.QTVs.Add(qtv);
            db.SaveChanges();
            return RedirectToAction("Login");


        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult ProcessLogin(LoginUser u)
        {
            var qTV = db.QTVs.SingleOrDefault(k => k.TenDN == u.User && k.MK == u.Pass);
            if (qTV == null)
            {
                ViewBag.TBLogin = "<div class=\"alert alert-danger\"> Tên Đăng nhập hoặc mật khẩu không đúng</div>";
                return View("Login");
            }
            else
            {
                Session["QTV"] = qTV;
                return RedirectToAction("Index", "ADMBooks");
            }
        }
        public ActionResult Logout()
        {
            if (Session["QTV"] != null)
            {
                Session.Remove("QTV");
            }

            return RedirectToAction("Index", "Books", new {Areas=""});
        }
    }
}

Controllers/AddTocartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using MVC_BookStore.Models;

namespace MVC_BookStore.Controllers
{
    public class AddTocartController : Controller
    {
        // GET: AddTocart
        DBBookStore db = new DBBookStore();
        public ActionResult AddToCart(int id)
        {
            //lấy giỏ hàng trong Session
            Cart cart = (Cart)Session["GIOHANG"];
            if (cart == null) //nếu giỏ hàng rỗng
            {
                cart = new Cart(); //tạo giỏ hàng
                Session["GIOHANG"] = cart;//lưu vào Session
            }
            //tìm đối tượng sách theo id
            var sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            //thêm sản phẩm sách vào giỏ hàng
            cart.AddItem(sach, 1);
            //chuyển hướng đến action Xem giỏ hàng
            return RedirectToAction("ViewCart");
        }
        //action trình bày giỏ hàng
        public ActionResult ViewCart()
        {
            Cart cart = (Cart)Session["GIOHANG"];
            if (cart == null)
            {
                cart = new Cart();
                Session["GIOHANG"] = cart;
            }
            return View(cart);
        }
        public ActionResult Update(int id, int soluong)
        {
            //tìm đối tượng trong CSDL
            var sach = db.Saches.Find(id);
            //lấy giỏ hàng trong session
            Cart cart = (Cart)Session["GIOHANG"];
            if (cart != null)
            {
                cart.UpdateItem(sach, soluong);
            }
            //chuyển hướng về lại actuon ViewCart
            return RedirectToAction("ViewCart");
        }
        public ActionResult Delete(int id)
        {
            //tìm đối tượng trong CSDL
            var sach = db.Saches.Find(id);
            //lấy giỏ hàng trong session
            Cart cart = (Cart)Session["GIOHANG"];
            if (cart != null)
            {
                cart.DeleteItem(sach);
            }
            //chuyển hướng về lại actuon ViewCart
            return RedirectToAction("ViewCart");
        }
        //xóa toang bộ giỏ hàng
        public ActionResult DeleteCart()
        {
            //lấy giỏ hàng trong session
            Cart cart = (Cart)Session["GIOHANG"];
            if (cart != null)
            {
                cart.Items.Clear();
            }
            //chuyển hướng về lại actuon ViewCart
            return RedirectToAction("ViewCart");
        }
        public ActionResult CoutItem()
        {
            int dem = 0;
            //lấy giỏ hàng trong sesstion của khách
            Cart cart = (Cart)Session["GIOHANG"];
            if (cart != null)
            {
                dem = cart.Items.Count;
            }
            return Content(dem.ToString());
        }
        public ActionResult Checkout()
        {
            if (Session["User"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            else
            {
                ViewBag.GIOHANG = Session["GIOHANG"];
                ViewBag.KHACHHANG = Session["User"];
            }
            return View(); 
        }
        public ActionResult ProcessOder(DonDatHang model)
        {
            //lay thong tin gio hang
            var cart = (Cart)Session["GIOHANG"];
            var kh = (KhachHang)Session["User"];
            //khoi tao don hang
            model.MaKH = kh.MaKH;
            model.NgayDH = DateTime.Today;
            model.Trigia = (decimal)cart.TongThanhTien;
            model.Dagiao = false;
            //add don hang vao csdl
            db.DonDatHangs.Add(model);
            db.SaveChanges();
            //add du lieu chi tiet don dat hang vao csdl
            foreach(var item in cart.Items)
            {
                db.CTDatHangs.Add(new CTDatHang
                {
                    SoDH = model.SoDH,
                    MaSach = item.Sach.MaSach,
                    Soluong = item.SoLuong,
                    Dongia=item.Sach.Dongia,
                    Thanhtien=(decimal)item.ThanhTien
                }) ;
                db.SaveChanges();
            }
            Session.Remove("GIOHANG");
            return RedirectToAction("Notify");
        }
        public ActionResult Notify()
        {
            return View();
        }
    }
}

Controllers/BooksController.cs
using MVC_BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace MVC_BookStore.Controllers
{
    public class BooksController : Controller
    {
        
        // Hiện 6 quyển sách ở mỗi trang từ mới đến cũ
        DBBookStore db= new DBBookStore();
        public ActionResult Index(int page=1)
        {
            var books = db.Saches.OrderByDescending(book => book.Ngaycapnhat).ToList();
            int pageSize = 6;
            return View(books.ToPagedList(page,pageSize));
        }
        // lấy sachs theo đề
        public ActionResult MenuChuDe()
        {
            var dsChuDe = db.ChuDes.ToList();
            return PartialView(dsChuDe);
        }
        public ActionResult SachTheoChuDe(int id, int page = 1)
        {
            var dsSach = db.Saches.Where(x => x.MaCD == id).ToList();
            ViewBag.TieuDe = db.ChuDes.Find(id).Tenchude.ToUpper();
            var pagesize = 6;
            return View(dsSach.ToPagedList(page, pagesize));
        }
        public ActionResult ChiTiet(int? id)
        {
            if (id == null)//nếu action không nhân id
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var sach = db.Saches.Find(id);
            if (sach == null) //nếu không tìm thấy sách
            {
                return HttpNotFound();
            }
            return View(sach);
        }
    }
}

Controllers/UsersController.cs
using MVC_BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_BookStore.Controllers
{
    public class UsersController : Controller
    {
        DBBookStore db = new DBBookStore();
        // GET: Users
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult ProcessRegister(RegisterUser u)
        {
            var kh = new KhachHang
            {
                HoTenKH = u.Name,
                TenDN = u.User,
                Matkhau = u.Pass,
                Ngaysinh = u.Born,
                Diachi = u.Address,
                Dienthoai = u.Phone,
                Email = u.Email,
            };
            db.KhachHangs.Add(kh);
            db.SaveChanges();
            return RedirectToAction("Login");


        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult ProcessLogin(LoginUser u)
        {
            var kh = db.KhachHangs.SingleOrDefault(k => k.TenDN == u.User && k.Matkhau ==u.Pass);
            if (kh == null)
            {
                ViewBag.TBLogin = "<div class=\"alert alert-danger\"> Tên Đăng nhập hoặc mật khẩu không đúng</div>";
                return View("Login");
            }
            else
            {
                Session["User"] = kh;
                return RedirectToAction("Index", "Books");
            }
        }
        public ActionResult Logout()
        {
            if (Session["User"] != null)
            {
                Session.Remove("User");
            }

            return RedirectToAction("Index", "Books");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BookStore Online", "Index", "Books", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Trang chủ", "Index", "Books")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Chủ đề sách
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            @Html.Action("MenuChuDe", "Books")
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                    <li>@Html.ActionLink("QUẢN TRỊ VIÊN", "Login", "Admins", new { area = "Admin" }, new { @class = "navbar-brand" })</li>
                   
                    <li>
                        <a href="@Url.Action("ViewCart","AddTocart")">
                            <span class="glyphicon glyphicon-shopping-cart"></span>Giỏ hàng (@Html.Action("CoutItem", "AddTocart"))
                        </a>
                    </li>
                    <li>
                        @if (Session["User"] != null)
                        {
                            <a href="@Url.Action("Logout", "Users")"> Đăng xuất</a>
                        }
                        else
                        {
                            <a href="@Url.Action("Login", "Users")"> Đăng nhập</a>
                        }
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>