Areas/Admin/Controllers/AdminsController.cs
using MVC_BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_BookStore.Areas.Admin.Controllers
{
    public class AdminsController : Controller
    {
        DBBookStore db= new DBBookStore();
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult ProcessRegister(RegisterUser u)
        {
            var qtv = new QTV
            {
                HoTen = u.Name,
                TenDN = u.User,
                MK = u.Pass,
                NgaySinh = u.Born,
                
                SDT = u.Phone,
                Email = u.Email,
            };
            db.QTVs.Add(qtv);
            db.SaveChanges();
            return RedirectToAction("Login");


        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult ProcessLogin(LoginUser u)
        {
            var qTV = db.QTVs.SingleOrDefault(k => k.TenDN == u.User && k.MK == u.Pass);
            if (qTV == null)
            {
                ViewBag.TBLogin = "<div class=\"alert alert-danger\"> Tên Đăng nhập hoặc mật khẩu không đúng</div>";
                return View("Login");
            }
            else
            {
                Session["QTV"] = qTV;
                return RedirectToAction("Index", "ADMBooks");
            }
        }
        public ActionResult Logout()
        {
            if (Session["QTV"] != null)
            {
                Session.Remove("QTV");
            }

            return RedirectToAction("Index", "Books", new {Areas=""});
        }
    }
}

Areas/Admin/Controllers/OdersController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using MVC_BookStore.Models;
using PagedList;
namespace MVC_BookStore.Areas.Admin.Controllers
{
    public class OdersController : Controller
    {
        // GET: Admin/Oders
        DBBookStore db= new DBBookStore();
        public ActionResult Index(int page=1)
        {
            var oders = db.DonDatHangs.OrderByDescending(x => x.NgayDH).ToList();
            return View(oders.ToPagedList(page, 10));
        }
        public ActionResult Detail(int id)
        {
            var TinhTrang = new ArrayList();
            TinhTrang.Add(new { check = true ,TT="Đã giao"}) ;
            TinhTrang.Add(new { check = false, TT = "Chưa giao" });
            ViewBag.TinhTrang = new SelectList(TinhTrang, "check", "TT");
            var oder = db.DonDatHangs.Find(id);
            return View(oder);
        }
        [HttpPost]
        public ActionResult Update(DonDatHang model)
        {
            var oder = db.DonDatHangs.FirstOrDefault(a=>a.SoDH==model.SoDH);
            if (model.Dagiao == true)
            {
                oder.Dagiao = true;
            }
            else
            {
                oder.Dagiao = false;
            }
            
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            var oder = db.DonDatHangs.Find(id);
            var CT = db.CTDatHangs.Where(x => x.SoDH == id).ToList();
            foreach (var item in CT)
            {
                db.CTDatHangs.Remove(item);
            }
            db.DonDatHangs.Remove(oder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/BooksController.cs
using MVC_BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace MVC_BookStore.Controllers
{
    public class BooksController : Controller
    {
        
        // Hiện 6 quyển sách ở mỗi trang từ mới đến cũ
        DBBookStore db= new DBBookStore();
        public ActionResult Index(int page=1)
        {
            var books = db.Saches.OrderByDescending(book => book.Ngaycapnhat).ToList();
            int pageSize = 6;
            return View(books.ToPagedList(page,pageSize));
        }
        // lấy sachs theo đề
        public ActionResult MenuChuDe()
        {
            var dsChuDe = db.ChuDes.ToList();
            return PartialView(dsChuDe);
        }
        public ActionResult SachTheoChuDe(int id, int page = 1)
        {
            var dsSach = db.Saches.Where(x => x.MaCD == id).ToList();
            ViewBag.TieuDe = db.ChuDes.Find(id).Tenchude.ToUpper();
            var pagesize = 6;
            return View(dsSach.ToPagedList(page, pagesize));
        }
        public ActionResult ChiTiet(int? id)
        {
            if (id == null)//nếu action không nhân id
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var sach = db.Saches.Find(id);
            if (sach == null) //nếu không tìm thấy sách
            {
                return HttpNotFound();
            }
            return View(sach);
        }
    }
}

Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Quản Trị Viên", "Index", "ADMBooks", new { area = "Admin" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Quản trị sách", "Index", "ADMBooks")</li>
                    <li>@Html.ActionLink("Quản lý đơn hàng", "Index", "Oders")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @if (Session["QTV"] != null)
                        {
                            @Html.ActionLink("Đăng xuất", "Index", "Books", new { area = "" }, new { @class = "navbar-brand" })

                        }
                        else
                        {
                            @Html.ActionLink("Đăng nhập", "Login", "Admins", new { area = "Admin" }, new { @class = "navbar-brand" })
                        }
                    </li>
                </ul>
            </div>
            
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>